### ISSUE TITLE
Refactor instances of driver.close() to driver.quit()

### ISSUE THREAD

**Issue by Thomas-McLaughlin** [Thomas-McLaughlin/WardrobeWizard2#41]
driver.quit() more reliably kills the webdriver process, making it less likely to create orphaned processes that occupy memory and do nothing.

**Comment by Ckrielle** [comment]
Hello there, just to be sure essentially what needs to be done is every instance of driver.close() needs to be written to driver.quit()?

**Comment by Thomas-McLaughlin** [comment]
Yes, that's it. I have been reading that driver.quit has a more graceful exit than driver.close()

If you're interested in doing this task, be sure to make a new branch for the changes :)
